name: fintech_multi_card_app
description: Prototipo de billetera centralizada de saldos y pagos NFC.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Iconos de Cupertino (iOS)
  cupertino_icons: ^1.0.6
  # Para peticiones HTTP asíncronas a APIs bancarias
  http: ^1.2.0
  # Para manejo y simulación de lectura/escritura NFC en el celular
  nfc_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
